### PR TITLE
Feat/virt secondary

### PR DESCRIPTION
**Pull request by eu-siemann**

### CODE REVIEW

**Comment by eu-siemann** [comment]
I cannot add other team members as reviewers, unfortunately

**Review by pattivacek — COMMENTED** [review]
Looks fine, although I'd prefer if "Secondary" were capitalized in log messages. And did we ever try to get CI for this repo?

**Comment by eu-siemann** [comment]
@patrickvacek 
> Looks fine, although I'd prefer if "Secondary" were capitalized in log messages.

Done.

> And did we ever try to get CI for this repo?

I've set up a simple CI, so we at least don't merge the code that fails to build.
Also, take a look at clang-tidy integration. Maybe we can simplify clang-tidy logic also for aktualizr in a similar way. Works only from Cmake 3.7, though.

**Review by pattivacek — APPROVED** [review]
Thanks for getting the CI working nicely!

**Pull request merged**
