### PR TITLE
Copying missing changes from aktualizr's hmi-stub.

### PR DESCRIPTION
**Pull request by pattivacek**

### CODE REVIEW

**Comment by eu-siemann** [comment]
I think I intentionally removed some bits that are present in hmi_stub. Don't remember why I removed SSL_error_strings, though.

**Comment by pattivacek** [comment]
> I think I intentionally removed some bits that are present in hmi_stub. Don't remember why I removed SSL_error_strings, though.

That's no problem, I was just trying to make sure we didn't lose anything important before we merged https://github.com/advancedtelematic/aktualizr/pull/1310 and removed hmi-stub. If this PR is bogus, we can close it. Unfortunately, I wasn't able to test it with ease.

**Comment by eu-siemann** [comment]
Yes, that makes sense if we remove hmi_stub. Let me double-check what is worth keeping here.

**Comment by pattivacek** [comment]
I removed a couple bits because I realized they were useless. I hadn't looked closely enough at what I was adding.

**Pull request merged**
